# Generated by Django 6.1 on 2026-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('plane_r2', models.FloatField(blank=True, null=True)),
                ('residual_relief', models.FloatField(blank=True, null=True)),
                ('structure_alignment', models.FloatField(blank=True, null=True)),
                ('georeferenced', models.BooleanField(default=False)),
                ('calibrated', models.BooleanField(default=False)),
                ('has_glb', models.BooleanField(default=False)),
                ('metrics_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
