export const gamusScenes = [
  {
    id: "DC_03_24",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_03_24-rgb.jpg",
    height: "/train-DC_03_24-height.jpg",
    depth: "/train-DC_03_24-depth.jpg",
    classes: "/train-DC_03_24-classes.jpg",
    thumb: "/train-DC_03_24-rgb.jpg",
    max: "38.6 m",
    buildingCoverage: 16.8,
    urban: false,
    split: "train",
  },
  {
    id: "DC_03_25",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_03_25-rgb.jpg",
    height: "/train-DC_03_25-height.jpg",
    depth: "/train-DC_03_25-depth.jpg",
    classes: "/train-DC_03_25-classes.jpg",
    thumb: "/train-DC_03_25-rgb.jpg",
    max: "34.6 m",
    buildingCoverage: 18.4,
    urban: false,
    split: "train",
  },
  {
    id: "DC_03_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_03_27-rgb.jpg",
    height: "/train-DC_03_27-height.jpg",
    depth: "/train-DC_03_27-depth.jpg",
    classes: "/train-DC_03_27-classes.jpg",
    thumb: "/train-DC_03_27-rgb.jpg",
    max: "25.2 m",
    buildingCoverage: 24.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_03_28",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_03_28-rgb.jpg",
    height: "/train-DC_03_28-height.jpg",
    depth: "/train-DC_03_28-depth.jpg",
    classes: "/train-DC_03_28-classes.jpg",
    thumb: "/train-DC_03_28-rgb.jpg",
    max: "45.3 m",
    buildingCoverage: 26.2,
    urban: true,
    split: "train",
  },
  {
    id: "DC_04_24",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_04_24-rgb.jpg",
    height: "/train-DC_04_24-height.jpg",
    depth: "/train-DC_04_24-depth.jpg",
    classes: "/train-DC_04_24-classes.jpg",
    thumb: "/train-DC_04_24-rgb.jpg",
    max: "33.4 m",
    buildingCoverage: 18.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_04_25",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_04_25-rgb.jpg",
    height: "/train-DC_04_25-height.jpg",
    depth: "/train-DC_04_25-depth.jpg",
    classes: "/train-DC_04_25-classes.jpg",
    thumb: "/train-DC_04_25-rgb.jpg",
    max: "35.9 m",
    buildingCoverage: 12.7,
    urban: false,
    split: "train",
  },
  {
    id: "DC_04_26",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_04_26-rgb.jpg",
    height: "/train-DC_04_26-height.jpg",
    depth: "/train-DC_04_26-depth.jpg",
    classes: "/train-DC_04_26-classes.jpg",
    thumb: "/train-DC_04_26-rgb.jpg",
    max: "34.0 m",
    buildingCoverage: 20.6,
    urban: false,
    split: "train",
  },
  {
    id: "DC_04_28",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_04_28-rgb.jpg",
    height: "/train-DC_04_28-height.jpg",
    depth: "/train-DC_04_28-depth.jpg",
    classes: "/train-DC_04_28-classes.jpg",
    thumb: "/train-DC_04_28-rgb.jpg",
    max: "28.7 m",
    buildingCoverage: 23.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_05_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_05_20-rgb.jpg",
    height: "/train-DC_05_20-height.jpg",
    depth: "/train-DC_05_20-depth.jpg",
    classes: "/train-DC_05_20-classes.jpg",
    thumb: "/train-DC_05_20-rgb.jpg",
    max: "31.5 m",
    buildingCoverage: 17.1,
    urban: false,
    split: "train",
  },
  {
    id: "DC_05_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_05_21-rgb.jpg",
    height: "/train-DC_05_21-height.jpg",
    depth: "/train-DC_05_21-depth.jpg",
    classes: "/train-DC_05_21-classes.jpg",
    thumb: "/train-DC_05_21-rgb.jpg",
    max: "41.0 m",
    buildingCoverage: 13.8,
    urban: false,
    split: "train",
  },
  {
    id: "DC_05_26",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_05_26-rgb.jpg",
    height: "/train-DC_05_26-height.jpg",
    depth: "/train-DC_05_26-depth.jpg",
    classes: "/train-DC_05_26-classes.jpg",
    thumb: "/train-DC_05_26-rgb.jpg",
    max: "37.3 m",
    buildingCoverage: 16.7,
    urban: false,
    split: "train",
  },
  {
    id: "DC_05_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_05_27-rgb.jpg",
    height: "/train-DC_05_27-height.jpg",
    depth: "/train-DC_05_27-depth.jpg",
    classes: "/train-DC_05_27-classes.jpg",
    thumb: "/train-DC_05_27-rgb.jpg",
    max: "27.0 m",
    buildingCoverage: 24.7,
    urban: false,
    split: "train",
  },
  {
    id: "DC_05_29",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_05_29-rgb.jpg",
    height: "/train-DC_05_29-height.jpg",
    depth: "/train-DC_05_29-depth.jpg",
    classes: "/train-DC_05_29-classes.jpg",
    thumb: "/train-DC_05_29-rgb.jpg",
    max: "26.9 m",
    buildingCoverage: 25.3,
    urban: true,
    split: "train",
  },
  {
    id: "DC_06_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_20-rgb.jpg",
    height: "/train-DC_06_20-height.jpg",
    depth: "/train-DC_06_20-depth.jpg",
    classes: "/train-DC_06_20-classes.jpg",
    thumb: "/train-DC_06_20-rgb.jpg",
    max: "28.7 m",
    buildingCoverage: 21.3,
    urban: false,
    split: "train",
  },
  {
    id: "DC_06_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_21-rgb.jpg",
    height: "/train-DC_06_21-height.jpg",
    depth: "/train-DC_06_21-depth.jpg",
    classes: "/train-DC_06_21-classes.jpg",
    thumb: "/train-DC_06_21-rgb.jpg",
    max: "31.0 m",
    buildingCoverage: 22.6,
    urban: false,
    split: "train",
  },
  {
    id: "DC_06_26",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_26-rgb.jpg",
    height: "/train-DC_06_26-height.jpg",
    depth: "/train-DC_06_26-depth.jpg",
    classes: "/train-DC_06_26-classes.jpg",
    thumb: "/train-DC_06_26-rgb.jpg",
    max: "34.7 m",
    buildingCoverage: 13.8,
    urban: false,
    split: "train",
  },
  {
    id: "DC_06_27",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_27-rgb.jpg",
    height: "/train-DC_06_27-height.jpg",
    depth: "/train-DC_06_27-depth.jpg",
    classes: "/train-DC_06_27-classes.jpg",
    thumb: "/train-DC_06_27-rgb.jpg",
    max: "24.9 m",
    buildingCoverage: 25.3,
    urban: true,
    split: "train",
  },
  {
    id: "DC_06_28",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_28-rgb.jpg",
    height: "/train-DC_06_28-height.jpg",
    depth: "/train-DC_06_28-depth.jpg",
    classes: "/train-DC_06_28-classes.jpg",
    thumb: "/train-DC_06_28-rgb.jpg",
    max: "24.8 m",
    buildingCoverage: 24.8,
    urban: false,
    split: "train",
  },
  {
    id: "DC_06_29",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_29-rgb.jpg",
    height: "/train-DC_06_29-height.jpg",
    depth: "/train-DC_06_29-depth.jpg",
    classes: "/train-DC_06_29-classes.jpg",
    thumb: "/train-DC_06_29-rgb.jpg",
    max: "17.0 m",
    buildingCoverage: 26.6,
    urban: true,
    split: "train",
  },
  {
    id: "DC_06_30",
    label: "Urban building fabric",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_30-rgb.jpg",
    height: "/train-DC_06_30-height.jpg",
    depth: "/train-DC_06_30-depth.jpg",
    classes: "/train-DC_06_30-classes.jpg",
    thumb: "/train-DC_06_30-rgb.jpg",
    max: "18.5 m",
    buildingCoverage: 30.9,
    urban: true,
    split: "train",
  },
  {
    id: "DC_06_31",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_06_31-rgb.jpg",
    height: "/train-DC_06_31-height.jpg",
    depth: "/train-DC_06_31-depth.jpg",
    classes: "/train-DC_06_31-classes.jpg",
    thumb: "/train-DC_06_31-rgb.jpg",
    max: "18.6 m",
    buildingCoverage: 21.0,
    urban: false,
    split: "train",
  },
  {
    id: "DC_07_19",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_07_19-rgb.jpg",
    height: "/train-DC_07_19-height.jpg",
    depth: "/train-DC_07_19-depth.jpg",
    classes: "/train-DC_07_19-classes.jpg",
    thumb: "/train-DC_07_19-rgb.jpg",
    max: "27.7 m",
    buildingCoverage: 18.7,
    urban: false,
    split: "train",
  },
  {
    id: "DC_07_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_07_20-rgb.jpg",
    height: "/train-DC_07_20-height.jpg",
    depth: "/train-DC_07_20-depth.jpg",
    classes: "/train-DC_07_20-classes.jpg",
    thumb: "/train-DC_07_20-rgb.jpg",
    max: "30.2 m",
    buildingCoverage: 21.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_07_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_07_27-rgb.jpg",
    height: "/train-DC_07_27-height.jpg",
    depth: "/train-DC_07_27-depth.jpg",
    classes: "/train-DC_07_27-classes.jpg",
    thumb: "/train-DC_07_27-rgb.jpg",
    max: "40.3 m",
    buildingCoverage: 19.3,
    urban: false,
    split: "train",
  },
  {
    id: "DC_07_28",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_07_28-rgb.jpg",
    height: "/train-DC_07_28-height.jpg",
    depth: "/train-DC_07_28-depth.jpg",
    classes: "/train-DC_07_28-classes.jpg",
    thumb: "/train-DC_07_28-rgb.jpg",
    max: "21.1 m",
    buildingCoverage: 27.8,
    urban: true,
    split: "train",
  },
  {
    id: "DC_07_30",
    label: "Urban building fabric",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_07_30-rgb.jpg",
    height: "/train-DC_07_30-height.jpg",
    depth: "/train-DC_07_30-depth.jpg",
    classes: "/train-DC_07_30-classes.jpg",
    thumb: "/train-DC_07_30-rgb.jpg",
    max: "19.4 m",
    buildingCoverage: 30.1,
    urban: true,
    split: "train",
  },
  {
    id: "DC_07_31",
    label: "Urban building fabric",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_07_31-rgb.jpg",
    height: "/train-DC_07_31-height.jpg",
    depth: "/train-DC_07_31-depth.jpg",
    classes: "/train-DC_07_31-classes.jpg",
    thumb: "/train-DC_07_31-rgb.jpg",
    max: "20.2 m",
    buildingCoverage: 30.5,
    urban: true,
    split: "train",
  },
  {
    id: "DC_08_17",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_17-rgb.jpg",
    height: "/train-DC_08_17-height.jpg",
    depth: "/train-DC_08_17-depth.jpg",
    classes: "/train-DC_08_17-classes.jpg",
    thumb: "/train-DC_08_17-rgb.jpg",
    max: "36.6 m",
    buildingCoverage: 17.7,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_18",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_18-rgb.jpg",
    height: "/train-DC_08_18-height.jpg",
    depth: "/train-DC_08_18-depth.jpg",
    classes: "/train-DC_08_18-classes.jpg",
    thumb: "/train-DC_08_18-rgb.jpg",
    max: "34.8 m",
    buildingCoverage: 18.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_19",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_19-rgb.jpg",
    height: "/train-DC_08_19-height.jpg",
    depth: "/train-DC_08_19-depth.jpg",
    classes: "/train-DC_08_19-classes.jpg",
    thumb: "/train-DC_08_19-rgb.jpg",
    max: "35.2 m",
    buildingCoverage: 14.1,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_20-rgb.jpg",
    height: "/train-DC_08_20-height.jpg",
    depth: "/train-DC_08_20-depth.jpg",
    classes: "/train-DC_08_20-classes.jpg",
    thumb: "/train-DC_08_20-rgb.jpg",
    max: "38.5 m",
    buildingCoverage: 13.9,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_21-rgb.jpg",
    height: "/train-DC_08_21-height.jpg",
    depth: "/train-DC_08_21-depth.jpg",
    classes: "/train-DC_08_21-classes.jpg",
    thumb: "/train-DC_08_21-rgb.jpg",
    max: "37.8 m",
    buildingCoverage: 11.8,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_28",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_28-rgb.jpg",
    height: "/train-DC_08_28-height.jpg",
    depth: "/train-DC_08_28-depth.jpg",
    classes: "/train-DC_08_28-classes.jpg",
    thumb: "/train-DC_08_28-rgb.jpg",
    max: "26.3 m",
    buildingCoverage: 29.5,
    urban: true,
    split: "train",
  },
  {
    id: "DC_08_29",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_29-rgb.jpg",
    height: "/train-DC_08_29-height.jpg",
    depth: "/train-DC_08_29-depth.jpg",
    classes: "/train-DC_08_29-classes.jpg",
    thumb: "/train-DC_08_29-rgb.jpg",
    max: "19.5 m",
    buildingCoverage: 14.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_30",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_30-rgb.jpg",
    height: "/train-DC_08_30-height.jpg",
    depth: "/train-DC_08_30-depth.jpg",
    classes: "/train-DC_08_30-classes.jpg",
    thumb: "/train-DC_08_30-rgb.jpg",
    max: "21.6 m",
    buildingCoverage: 23.6,
    urban: false,
    split: "train",
  },
  {
    id: "DC_08_32",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_08_32-rgb.jpg",
    height: "/train-DC_08_32-height.jpg",
    depth: "/train-DC_08_32-depth.jpg",
    classes: "/train-DC_08_32-classes.jpg",
    thumb: "/train-DC_08_32-rgb.jpg",
    max: "22.8 m",
    buildingCoverage: 19.0,
    urban: false,
    split: "train",
  },
  {
    id: "DC_09_17",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_17-rgb.jpg",
    height: "/train-DC_09_17-height.jpg",
    depth: "/train-DC_09_17-depth.jpg",
    classes: "/train-DC_09_17-classes.jpg",
    thumb: "/train-DC_09_17-rgb.jpg",
    max: "34.3 m",
    buildingCoverage: 18.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_09_19",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_19-rgb.jpg",
    height: "/train-DC_09_19-height.jpg",
    depth: "/train-DC_09_19-depth.jpg",
    classes: "/train-DC_09_19-classes.jpg",
    thumb: "/train-DC_09_19-rgb.jpg",
    max: "33.6 m",
    buildingCoverage: 23.4,
    urban: false,
    split: "train",
  },
  {
    id: "DC_09_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_20-rgb.jpg",
    height: "/train-DC_09_20-height.jpg",
    depth: "/train-DC_09_20-depth.jpg",
    classes: "/train-DC_09_20-classes.jpg",
    thumb: "/train-DC_09_20-rgb.jpg",
    max: "34.2 m",
    buildingCoverage: 19.2,
    urban: false,
    split: "train",
  },
  {
    id: "DC_09_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_21-rgb.jpg",
    height: "/train-DC_09_21-height.jpg",
    depth: "/train-DC_09_21-depth.jpg",
    classes: "/train-DC_09_21-classes.jpg",
    thumb: "/train-DC_09_21-rgb.jpg",
    max: "35.9 m",
    buildingCoverage: 20.4,
    urban: false,
    split: "train",
  },
  {
    id: "DC_09_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_27-rgb.jpg",
    height: "/train-DC_09_27-height.jpg",
    depth: "/train-DC_09_27-depth.jpg",
    classes: "/train-DC_09_27-classes.jpg",
    thumb: "/train-DC_09_27-rgb.jpg",
    max: "41.4 m",
    buildingCoverage: 7.1,
    urban: false,
    split: "train",
  },
  {
    id: "DC_09_28",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_28-rgb.jpg",
    height: "/train-DC_09_28-height.jpg",
    depth: "/train-DC_09_28-depth.jpg",
    classes: "/train-DC_09_28-classes.jpg",
    thumb: "/train-DC_09_28-rgb.jpg",
    max: "31.0 m",
    buildingCoverage: 27.6,
    urban: true,
    split: "train",
  },
  {
    id: "DC_09_30",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_30-rgb.jpg",
    height: "/train-DC_09_30-height.jpg",
    depth: "/train-DC_09_30-depth.jpg",
    classes: "/train-DC_09_30-classes.jpg",
    thumb: "/train-DC_09_30-rgb.jpg",
    max: "18.7 m",
    buildingCoverage: 29.4,
    urban: true,
    split: "train",
  },
  {
    id: "DC_09_31",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_09_31-rgb.jpg",
    height: "/train-DC_09_31-height.jpg",
    depth: "/train-DC_09_31-depth.jpg",
    classes: "/train-DC_09_31-classes.jpg",
    thumb: "/train-DC_09_31-rgb.jpg",
    max: "22.4 m",
    buildingCoverage: 22.9,
    urban: false,
    split: "train",
  },
  {
    id: "DC_10_16",
    label: "Mixed urban district",
    coord: "DFC 2019 · train tile",
    rgb: "/train-DC_10_16-rgb.jpg",
    height: "/train-DC_10_16-height.jpg",
    depth: "/train-DC_10_16-depth.jpg",
    classes: "/train-DC_10_16-classes.jpg",
    thumb: "/train-DC_10_16-rgb.jpg",
    max: "36.2 m",
    buildingCoverage: 28.8,
    urban: true,
    split: "train",
  },
  {
    id: "DC_10_30",
    label: "Dense building blocks",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_10_30-rgb.jpg",
    height: "/val-DC_10_30-height.jpg",
    depth: "/val-DC_10_30-depth.jpg",
    classes: "/val-DC_10_30-classes.jpg",
    thumb: "/val-DC_10_30-rgb.jpg",
    max: "24.9 m",
    buildingCoverage: 36.4,
    urban: true,
    split: "val",
  },
  {
    id: "DC_11_16",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_11_16-rgb.jpg",
    height: "/val-DC_11_16-height.jpg",
    depth: "/val-DC_11_16-depth.jpg",
    classes: "/val-DC_11_16-classes.jpg",
    thumb: "/val-DC_11_16-rgb.jpg",
    max: "25.1 m",
    buildingCoverage: 28.4,
    urban: true,
    split: "val",
  },
  {
    id: "DC_11_33",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_11_33-rgb.jpg",
    height: "/val-DC_11_33-height.jpg",
    depth: "/val-DC_11_33-depth.jpg",
    classes: "/val-DC_11_33-classes.jpg",
    thumb: "/val-DC_11_33-rgb.jpg",
    max: "23.7 m",
    buildingCoverage: 11.8,
    urban: false,
    split: "val",
  },
  {
    id: "DC_11_34",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_11_34-rgb.jpg",
    height: "/val-DC_11_34-height.jpg",
    depth: "/val-DC_11_34-depth.jpg",
    classes: "/val-DC_11_34-classes.jpg",
    thumb: "/val-DC_11_34-rgb.jpg",
    max: "20.6 m",
    buildingCoverage: 19.9,
    urban: false,
    split: "val",
  },
  {
    id: "DC_12_17",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_12_17-rgb.jpg",
    height: "/val-DC_12_17-height.jpg",
    depth: "/val-DC_12_17-depth.jpg",
    classes: "/val-DC_12_17-classes.jpg",
    thumb: "/val-DC_12_17-rgb.jpg",
    max: "28.4 m",
    buildingCoverage: 23.2,
    urban: false,
    split: "val",
  },
  {
    id: "DC_12_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_12_27-rgb.jpg",
    height: "/val-DC_12_27-height.jpg",
    depth: "/val-DC_12_27-depth.jpg",
    classes: "/val-DC_12_27-classes.jpg",
    thumb: "/val-DC_12_27-rgb.jpg",
    max: "24.7 m",
    buildingCoverage: 23.9,
    urban: false,
    split: "val",
  },
  {
    id: "DC_13_14",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_13_14-rgb.jpg",
    height: "/val-DC_13_14-height.jpg",
    depth: "/val-DC_13_14-depth.jpg",
    classes: "/val-DC_13_14-classes.jpg",
    thumb: "/val-DC_13_14-rgb.jpg",
    max: "22.1 m",
    buildingCoverage: 29.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_13_15",
    label: "Urban building fabric",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_13_15-rgb.jpg",
    height: "/val-DC_13_15-height.jpg",
    depth: "/val-DC_13_15-depth.jpg",
    classes: "/val-DC_13_15-classes.jpg",
    thumb: "/val-DC_13_15-rgb.jpg",
    max: "26.2 m",
    buildingCoverage: 32.1,
    urban: true,
    split: "val",
  },
  {
    id: "DC_13_17",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_13_17-rgb.jpg",
    height: "/val-DC_13_17-height.jpg",
    depth: "/val-DC_13_17-depth.jpg",
    classes: "/val-DC_13_17-classes.jpg",
    thumb: "/val-DC_13_17-rgb.jpg",
    max: "30.7 m",
    buildingCoverage: 29.6,
    urban: true,
    split: "val",
  },
  {
    id: "DC_13_28",
    label: "Dense building blocks",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_13_28-rgb.jpg",
    height: "/val-DC_13_28-height.jpg",
    depth: "/val-DC_13_28-depth.jpg",
    classes: "/val-DC_13_28-classes.jpg",
    thumb: "/val-DC_13_28-rgb.jpg",
    max: "20.9 m",
    buildingCoverage: 38.4,
    urban: true,
    split: "val",
  },
  {
    id: "DC_13_34",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_13_34-rgb.jpg",
    height: "/val-DC_13_34-height.jpg",
    depth: "/val-DC_13_34-depth.jpg",
    classes: "/val-DC_13_34-classes.jpg",
    thumb: "/val-DC_13_34-rgb.jpg",
    max: "19.4 m",
    buildingCoverage: 26.2,
    urban: true,
    split: "val",
  },
  {
    id: "DC_14_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_14_21-rgb.jpg",
    height: "/val-DC_14_21-height.jpg",
    depth: "/val-DC_14_21-depth.jpg",
    classes: "/val-DC_14_21-classes.jpg",
    thumb: "/val-DC_14_21-rgb.jpg",
    max: "36.4 m",
    buildingCoverage: 12.9,
    urban: false,
    split: "val",
  },
  {
    id: "DC_14_24",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_14_24-rgb.jpg",
    height: "/val-DC_14_24-height.jpg",
    depth: "/val-DC_14_24-depth.jpg",
    classes: "/val-DC_14_24-classes.jpg",
    thumb: "/val-DC_14_24-rgb.jpg",
    max: "40.7 m",
    buildingCoverage: 0.2,
    urban: false,
    split: "val",
  },
  {
    id: "DC_14_32",
    label: "Dense building blocks",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_14_32-rgb.jpg",
    height: "/val-DC_14_32-height.jpg",
    depth: "/val-DC_14_32-depth.jpg",
    classes: "/val-DC_14_32-classes.jpg",
    thumb: "/val-DC_14_32-rgb.jpg",
    max: "18.6 m",
    buildingCoverage: 37.6,
    urban: true,
    split: "val",
  },
  {
    id: "DC_14_35",
    label: "Urban building fabric",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_14_35-rgb.jpg",
    height: "/val-DC_14_35-height.jpg",
    depth: "/val-DC_14_35-depth.jpg",
    classes: "/val-DC_14_35-classes.jpg",
    thumb: "/val-DC_14_35-rgb.jpg",
    max: "18.7 m",
    buildingCoverage: 34.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_15_13",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_13-rgb.jpg",
    height: "/val-DC_15_13-height.jpg",
    depth: "/val-DC_15_13-depth.jpg",
    classes: "/val-DC_15_13-classes.jpg",
    thumb: "/val-DC_15_13-rgb.jpg",
    max: "26.3 m",
    buildingCoverage: 28.3,
    urban: true,
    split: "val",
  },
  {
    id: "DC_15_15",
    label: "Urban building fabric",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_15-rgb.jpg",
    height: "/val-DC_15_15-height.jpg",
    depth: "/val-DC_15_15-depth.jpg",
    classes: "/val-DC_15_15-classes.jpg",
    thumb: "/val-DC_15_15-rgb.jpg",
    max: "32.0 m",
    buildingCoverage: 32.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_15_17",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_17-rgb.jpg",
    height: "/val-DC_15_17-height.jpg",
    depth: "/val-DC_15_17-depth.jpg",
    classes: "/val-DC_15_17-classes.jpg",
    thumb: "/val-DC_15_17-rgb.jpg",
    max: "26.2 m",
    buildingCoverage: 26.4,
    urban: true,
    split: "val",
  },
  {
    id: "DC_15_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_20-rgb.jpg",
    height: "/val-DC_15_20-height.jpg",
    depth: "/val-DC_15_20-depth.jpg",
    classes: "/val-DC_15_20-classes.jpg",
    thumb: "/val-DC_15_20-rgb.jpg",
    max: "31.5 m",
    buildingCoverage: 16.5,
    urban: false,
    split: "val",
  },
  {
    id: "DC_15_23",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_23-rgb.jpg",
    height: "/val-DC_15_23-height.jpg",
    depth: "/val-DC_15_23-depth.jpg",
    classes: "/val-DC_15_23-classes.jpg",
    thumb: "/val-DC_15_23-rgb.jpg",
    max: "42.7 m",
    buildingCoverage: 0.0,
    urban: false,
    split: "val",
  },
  {
    id: "DC_15_39",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_39-rgb.jpg",
    height: "/val-DC_15_39-height.jpg",
    depth: "/val-DC_15_39-depth.jpg",
    classes: "/val-DC_15_39-classes.jpg",
    thumb: "/val-DC_15_39-rgb.jpg",
    max: "14.6 m",
    buildingCoverage: 28.5,
    urban: true,
    split: "val",
  },
  {
    id: "DC_15_40",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_15_40-rgb.jpg",
    height: "/val-DC_15_40-height.jpg",
    depth: "/val-DC_15_40-depth.jpg",
    classes: "/val-DC_15_40-classes.jpg",
    thumb: "/val-DC_15_40-rgb.jpg",
    max: "15.2 m",
    buildingCoverage: 27.6,
    urban: true,
    split: "val",
  },
  {
    id: "DC_16_14",
    label: "Urban building fabric",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_16_14-rgb.jpg",
    height: "/val-DC_16_14-height.jpg",
    depth: "/val-DC_16_14-depth.jpg",
    classes: "/val-DC_16_14-classes.jpg",
    thumb: "/val-DC_16_14-rgb.jpg",
    max: "29.8 m",
    buildingCoverage: 31.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_16_15",
    label: "Dense building blocks",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_16_15-rgb.jpg",
    height: "/val-DC_16_15-height.jpg",
    depth: "/val-DC_16_15-depth.jpg",
    classes: "/val-DC_16_15-classes.jpg",
    thumb: "/val-DC_16_15-rgb.jpg",
    max: "30.0 m",
    buildingCoverage: 35.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_16_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_16_21-rgb.jpg",
    height: "/val-DC_16_21-height.jpg",
    depth: "/val-DC_16_21-depth.jpg",
    classes: "/val-DC_16_21-classes.jpg",
    thumb: "/val-DC_16_21-rgb.jpg",
    max: "38.7 m",
    buildingCoverage: 0.3,
    urban: false,
    split: "val",
  },
  {
    id: "DC_16_28",
    label: "Urban building fabric",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_16_28-rgb.jpg",
    height: "/val-DC_16_28-height.jpg",
    depth: "/val-DC_16_28-depth.jpg",
    classes: "/val-DC_16_28-classes.jpg",
    thumb: "/val-DC_16_28-rgb.jpg",
    max: "21.2 m",
    buildingCoverage: 32.1,
    urban: true,
    split: "val",
  },
  {
    id: "DC_16_33",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_16_33-rgb.jpg",
    height: "/val-DC_16_33-height.jpg",
    depth: "/val-DC_16_33-depth.jpg",
    classes: "/val-DC_16_33-classes.jpg",
    thumb: "/val-DC_16_33-rgb.jpg",
    max: "20.9 m",
    buildingCoverage: 25.5,
    urban: true,
    split: "val",
  },
  {
    id: "DC_16_37",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_16_37-rgb.jpg",
    height: "/val-DC_16_37-height.jpg",
    depth: "/val-DC_16_37-depth.jpg",
    classes: "/val-DC_16_37-classes.jpg",
    thumb: "/val-DC_16_37-rgb.jpg",
    max: "23.5 m",
    buildingCoverage: 24.4,
    urban: false,
    split: "val",
  },
  {
    id: "DC_17_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_17_20-rgb.jpg",
    height: "/val-DC_17_20-height.jpg",
    depth: "/val-DC_17_20-depth.jpg",
    classes: "/val-DC_17_20-classes.jpg",
    thumb: "/val-DC_17_20-rgb.jpg",
    max: "37.2 m",
    buildingCoverage: 1.1,
    urban: false,
    split: "val",
  },
  {
    id: "DC_17_36",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_17_36-rgb.jpg",
    height: "/val-DC_17_36-height.jpg",
    depth: "/val-DC_17_36-depth.jpg",
    classes: "/val-DC_17_36-classes.jpg",
    thumb: "/val-DC_17_36-rgb.jpg",
    max: "18.0 m",
    buildingCoverage: 24.9,
    urban: false,
    split: "val",
  },
  {
    id: "DC_17_37",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_17_37-rgb.jpg",
    height: "/val-DC_17_37-height.jpg",
    depth: "/val-DC_17_37-depth.jpg",
    classes: "/val-DC_17_37-classes.jpg",
    thumb: "/val-DC_17_37-rgb.jpg",
    max: "24.5 m",
    buildingCoverage: 11.4,
    urban: false,
    split: "val",
  },
  {
    id: "DC_17_38",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_17_38-rgb.jpg",
    height: "/val-DC_17_38-height.jpg",
    depth: "/val-DC_17_38-depth.jpg",
    classes: "/val-DC_17_38-classes.jpg",
    thumb: "/val-DC_17_38-rgb.jpg",
    max: "19.3 m",
    buildingCoverage: 9.3,
    urban: false,
    split: "val",
  },
  {
    id: "DC_18_13",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_18_13-rgb.jpg",
    height: "/val-DC_18_13-height.jpg",
    depth: "/val-DC_18_13-depth.jpg",
    classes: "/val-DC_18_13-classes.jpg",
    thumb: "/val-DC_18_13-rgb.jpg",
    max: "20.2 m",
    buildingCoverage: 8.3,
    urban: false,
    split: "val",
  },
  {
    id: "DC_18_17",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_18_17-rgb.jpg",
    height: "/val-DC_18_17-height.jpg",
    depth: "/val-DC_18_17-depth.jpg",
    classes: "/val-DC_18_17-classes.jpg",
    thumb: "/val-DC_18_17-rgb.jpg",
    max: "25.8 m",
    buildingCoverage: 20.4,
    urban: false,
    split: "val",
  },
  {
    id: "DC_18_24",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_18_24-rgb.jpg",
    height: "/val-DC_18_24-height.jpg",
    depth: "/val-DC_18_24-depth.jpg",
    classes: "/val-DC_18_24-classes.jpg",
    thumb: "/val-DC_18_24-rgb.jpg",
    max: "42.0 m",
    buildingCoverage: 0.0,
    urban: false,
    split: "val",
  },
  {
    id: "DC_18_28",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_18_28-rgb.jpg",
    height: "/val-DC_18_28-height.jpg",
    depth: "/val-DC_18_28-depth.jpg",
    classes: "/val-DC_18_28-classes.jpg",
    thumb: "/val-DC_18_28-rgb.jpg",
    max: "22.7 m",
    buildingCoverage: 28.5,
    urban: true,
    split: "val",
  },
  {
    id: "DC_18_39",
    label: "Dense building blocks",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_18_39-rgb.jpg",
    height: "/val-DC_18_39-height.jpg",
    depth: "/val-DC_18_39-depth.jpg",
    classes: "/val-DC_18_39-classes.jpg",
    thumb: "/val-DC_18_39-rgb.jpg",
    max: "24.7 m",
    buildingCoverage: 36.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_18_43",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_18_43-rgb.jpg",
    height: "/val-DC_18_43-height.jpg",
    depth: "/val-DC_18_43-depth.jpg",
    classes: "/val-DC_18_43-classes.jpg",
    thumb: "/val-DC_18_43-rgb.jpg",
    max: "25.4 m",
    buildingCoverage: 13.3,
    urban: false,
    split: "val",
  },
  {
    id: "DC_19_16",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_19_16-rgb.jpg",
    height: "/val-DC_19_16-height.jpg",
    depth: "/val-DC_19_16-depth.jpg",
    classes: "/val-DC_19_16-classes.jpg",
    thumb: "/val-DC_19_16-rgb.jpg",
    max: "27.5 m",
    buildingCoverage: 27.2,
    urban: true,
    split: "val",
  },
  {
    id: "DC_19_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_19_21-rgb.jpg",
    height: "/val-DC_19_21-height.jpg",
    depth: "/val-DC_19_21-depth.jpg",
    classes: "/val-DC_19_21-classes.jpg",
    thumb: "/val-DC_19_21-rgb.jpg",
    max: "36.0 m",
    buildingCoverage: 9.5,
    urban: false,
    split: "val",
  },
  {
    id: "DC_19_26",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_19_26-rgb.jpg",
    height: "/val-DC_19_26-height.jpg",
    depth: "/val-DC_19_26-depth.jpg",
    classes: "/val-DC_19_26-classes.jpg",
    thumb: "/val-DC_19_26-rgb.jpg",
    max: "31.5 m",
    buildingCoverage: 6.8,
    urban: false,
    split: "val",
  },
  {
    id: "DC_19_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_19_27-rgb.jpg",
    height: "/val-DC_19_27-height.jpg",
    depth: "/val-DC_19_27-depth.jpg",
    classes: "/val-DC_19_27-classes.jpg",
    thumb: "/val-DC_19_27-rgb.jpg",
    max: "22.1 m",
    buildingCoverage: 21.6,
    urban: false,
    split: "val",
  },
  {
    id: "DC_19_42",
    label: "Mixed urban district",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_19_42-rgb.jpg",
    height: "/val-DC_19_42-height.jpg",
    depth: "/val-DC_19_42-depth.jpg",
    classes: "/val-DC_19_42-classes.jpg",
    thumb: "/val-DC_19_42-rgb.jpg",
    max: "20.1 m",
    buildingCoverage: 28.7,
    urban: true,
    split: "val",
  },
  {
    id: "DC_20_07",
    label: "Urban building fabric",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_20_07-rgb.jpg",
    height: "/val-DC_20_07-height.jpg",
    depth: "/val-DC_20_07-depth.jpg",
    classes: "/val-DC_20_07-classes.jpg",
    thumb: "/val-DC_20_07-rgb.jpg",
    max: "22.8 m",
    buildingCoverage: 31.0,
    urban: true,
    split: "val",
  },
  {
    id: "DC_20_09",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · val tile",
    rgb: "/val-DC_20_09-rgb.jpg",
    height: "/val-DC_20_09-height.jpg",
    depth: "/val-DC_20_09-depth.jpg",
    classes: "/val-DC_20_09-classes.jpg",
    thumb: "/val-DC_20_09-rgb.jpg",
    max: "28.8 m",
    buildingCoverage: 23.9,
    urban: false,
    split: "val",
  },
  {
    id: "DC_08_27",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_08_27-rgb.jpg",
    height: "/test-DC_08_27-height.jpg",
    depth: "/test-DC_08_27-depth.jpg",
    classes: "/test-DC_08_27-classes.jpg",
    thumb: "/test-DC_08_27-rgb.jpg",
    max: "37.3 m",
    buildingCoverage: 17.4,
    urban: false,
    split: "test",
  },
  {
    id: "DC_09_18",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_09_18-rgb.jpg",
    height: "/test-DC_09_18-height.jpg",
    depth: "/test-DC_09_18-depth.jpg",
    classes: "/test-DC_09_18-classes.jpg",
    thumb: "/test-DC_09_18-rgb.jpg",
    max: "32.7 m",
    buildingCoverage: 22.8,
    urban: false,
    split: "test",
  },
  {
    id: "DC_09_29",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_09_29-rgb.jpg",
    height: "/test-DC_09_29-height.jpg",
    depth: "/test-DC_09_29-depth.jpg",
    classes: "/test-DC_09_29-classes.jpg",
    thumb: "/test-DC_09_29-rgb.jpg",
    max: "21.0 m",
    buildingCoverage: 23.4,
    urban: false,
    split: "test",
  },
  {
    id: "DC_09_32",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_09_32-rgb.jpg",
    height: "/test-DC_09_32-height.jpg",
    depth: "/test-DC_09_32-depth.jpg",
    classes: "/test-DC_09_32-classes.jpg",
    thumb: "/test-DC_09_32-rgb.jpg",
    max: "23.9 m",
    buildingCoverage: 26.3,
    urban: true,
    split: "test",
  },
  {
    id: "DC_10_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_10_20-rgb.jpg",
    height: "/test-DC_10_20-height.jpg",
    depth: "/test-DC_10_20-depth.jpg",
    classes: "/test-DC_10_20-classes.jpg",
    thumb: "/test-DC_10_20-rgb.jpg",
    max: "30.3 m",
    buildingCoverage: 19.9,
    urban: false,
    split: "test",
  },
  {
    id: "DC_10_29",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_10_29-rgb.jpg",
    height: "/test-DC_10_29-height.jpg",
    depth: "/test-DC_10_29-depth.jpg",
    classes: "/test-DC_10_29-classes.jpg",
    thumb: "/test-DC_10_29-rgb.jpg",
    max: "26.5 m",
    buildingCoverage: 23.8,
    urban: false,
    split: "test",
  },
  {
    id: "DC_11_15",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_11_15-rgb.jpg",
    height: "/test-DC_11_15-height.jpg",
    depth: "/test-DC_11_15-depth.jpg",
    classes: "/test-DC_11_15-classes.jpg",
    thumb: "/test-DC_11_15-rgb.jpg",
    max: "25.3 m",
    buildingCoverage: 23.6,
    urban: false,
    split: "test",
  },
  {
    id: "DC_11_19",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_11_19-rgb.jpg",
    height: "/test-DC_11_19-height.jpg",
    depth: "/test-DC_11_19-depth.jpg",
    classes: "/test-DC_11_19-classes.jpg",
    thumb: "/test-DC_11_19-rgb.jpg",
    max: "23.4 m",
    buildingCoverage: 25.8,
    urban: true,
    split: "test",
  },
  {
    id: "DC_11_31",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_11_31-rgb.jpg",
    height: "/test-DC_11_31-height.jpg",
    depth: "/test-DC_11_31-depth.jpg",
    classes: "/test-DC_11_31-classes.jpg",
    thumb: "/test-DC_11_31-rgb.jpg",
    max: "20.2 m",
    buildingCoverage: 29.1,
    urban: true,
    split: "test",
  },
  {
    id: "DC_11_32",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_11_32-rgb.jpg",
    height: "/test-DC_11_32-height.jpg",
    depth: "/test-DC_11_32-depth.jpg",
    classes: "/test-DC_11_32-classes.jpg",
    thumb: "/test-DC_11_32-rgb.jpg",
    max: "21.6 m",
    buildingCoverage: 25.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_12_15",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_12_15-rgb.jpg",
    height: "/test-DC_12_15-height.jpg",
    depth: "/test-DC_12_15-depth.jpg",
    classes: "/test-DC_12_15-classes.jpg",
    thumb: "/test-DC_12_15-rgb.jpg",
    max: "26.3 m",
    buildingCoverage: 26.0,
    urban: true,
    split: "test",
  },
  {
    id: "DC_12_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_12_20-rgb.jpg",
    height: "/test-DC_12_20-height.jpg",
    depth: "/test-DC_12_20-depth.jpg",
    classes: "/test-DC_12_20-classes.jpg",
    thumb: "/test-DC_12_20-rgb.jpg",
    max: "22.6 m",
    buildingCoverage: 23.2,
    urban: false,
    split: "test",
  },
  {
    id: "DC_12_34",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_12_34-rgb.jpg",
    height: "/test-DC_12_34-height.jpg",
    depth: "/test-DC_12_34-depth.jpg",
    classes: "/test-DC_12_34-classes.jpg",
    thumb: "/test-DC_12_34-rgb.jpg",
    max: "18.4 m",
    buildingCoverage: 25.0,
    urban: true,
    split: "test",
  },
  {
    id: "DC_12_35",
    label: "Dense building blocks",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_12_35-rgb.jpg",
    height: "/test-DC_12_35-height.jpg",
    depth: "/test-DC_12_35-depth.jpg",
    classes: "/test-DC_12_35-classes.jpg",
    thumb: "/test-DC_12_35-rgb.jpg",
    max: "21.6 m",
    buildingCoverage: 37.4,
    urban: true,
    split: "test",
  },
  {
    id: "DC_13_19",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_13_19-rgb.jpg",
    height: "/test-DC_13_19-height.jpg",
    depth: "/test-DC_13_19-depth.jpg",
    classes: "/test-DC_13_19-classes.jpg",
    thumb: "/test-DC_13_19-rgb.jpg",
    max: "22.1 m",
    buildingCoverage: 28.6,
    urban: true,
    split: "test",
  },
  {
    id: "DC_13_21",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_13_21-rgb.jpg",
    height: "/test-DC_13_21-height.jpg",
    depth: "/test-DC_13_21-depth.jpg",
    classes: "/test-DC_13_21-classes.jpg",
    thumb: "/test-DC_13_21-rgb.jpg",
    max: "43.7 m",
    buildingCoverage: 4.7,
    urban: false,
    split: "test",
  },
  {
    id: "DC_13_25",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_13_25-rgb.jpg",
    height: "/test-DC_13_25-height.jpg",
    depth: "/test-DC_13_25-depth.jpg",
    classes: "/test-DC_13_25-classes.jpg",
    thumb: "/test-DC_13_25-rgb.jpg",
    max: "38.5 m",
    buildingCoverage: 0.1,
    urban: false,
    split: "test",
  },
  {
    id: "DC_13_33",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_13_33-rgb.jpg",
    height: "/test-DC_13_33-height.jpg",
    depth: "/test-DC_13_33-depth.jpg",
    classes: "/test-DC_13_33-classes.jpg",
    thumb: "/test-DC_13_33-rgb.jpg",
    max: "17.9 m",
    buildingCoverage: 25.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_13_35",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_13_35-rgb.jpg",
    height: "/test-DC_13_35-height.jpg",
    depth: "/test-DC_13_35-depth.jpg",
    classes: "/test-DC_13_35-classes.jpg",
    thumb: "/test-DC_13_35-rgb.jpg",
    max: "17.1 m",
    buildingCoverage: 34.7,
    urban: true,
    split: "test",
  },
  {
    id: "DC_14_28",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_14_28-rgb.jpg",
    height: "/test-DC_14_28-height.jpg",
    depth: "/test-DC_14_28-depth.jpg",
    classes: "/test-DC_14_28-classes.jpg",
    thumb: "/test-DC_14_28-rgb.jpg",
    max: "24.6 m",
    buildingCoverage: 26.4,
    urban: true,
    split: "test",
  },
  {
    id: "DC_14_36",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_14_36-rgb.jpg",
    height: "/test-DC_14_36-height.jpg",
    depth: "/test-DC_14_36-depth.jpg",
    classes: "/test-DC_14_36-classes.jpg",
    thumb: "/test-DC_14_36-rgb.jpg",
    max: "19.7 m",
    buildingCoverage: 29.5,
    urban: true,
    split: "test",
  },
  {
    id: "DC_15_27",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_15_27-rgb.jpg",
    height: "/test-DC_15_27-height.jpg",
    depth: "/test-DC_15_27-depth.jpg",
    classes: "/test-DC_15_27-classes.jpg",
    thumb: "/test-DC_15_27-rgb.jpg",
    max: "25.6 m",
    buildingCoverage: 25.8,
    urban: true,
    split: "test",
  },
  {
    id: "DC_16_13",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_16_13-rgb.jpg",
    height: "/test-DC_16_13-height.jpg",
    depth: "/test-DC_16_13-depth.jpg",
    classes: "/test-DC_16_13-classes.jpg",
    thumb: "/test-DC_16_13-rgb.jpg",
    max: "27.8 m",
    buildingCoverage: 28.5,
    urban: true,
    split: "test",
  },
  {
    id: "DC_16_16",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_16_16-rgb.jpg",
    height: "/test-DC_16_16-height.jpg",
    depth: "/test-DC_16_16-depth.jpg",
    classes: "/test-DC_16_16-classes.jpg",
    thumb: "/test-DC_16_16-rgb.jpg",
    max: "30.2 m",
    buildingCoverage: 29.6,
    urban: true,
    split: "test",
  },
  {
    id: "DC_16_18",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_16_18-rgb.jpg",
    height: "/test-DC_16_18-height.jpg",
    depth: "/test-DC_16_18-depth.jpg",
    classes: "/test-DC_16_18-classes.jpg",
    thumb: "/test-DC_16_18-rgb.jpg",
    max: "32.4 m",
    buildingCoverage: 11.3,
    urban: false,
    split: "test",
  },
  {
    id: "DC_16_27",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_16_27-rgb.jpg",
    height: "/test-DC_16_27-height.jpg",
    depth: "/test-DC_16_27-depth.jpg",
    classes: "/test-DC_16_27-classes.jpg",
    thumb: "/test-DC_16_27-rgb.jpg",
    max: "20.1 m",
    buildingCoverage: 30.4,
    urban: true,
    split: "test",
  },
  {
    id: "DC_16_38",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_16_38-rgb.jpg",
    height: "/test-DC_16_38-height.jpg",
    depth: "/test-DC_16_38-depth.jpg",
    classes: "/test-DC_16_38-classes.jpg",
    thumb: "/test-DC_16_38-rgb.jpg",
    max: "18.7 m",
    buildingCoverage: 33.8,
    urban: true,
    split: "test",
  },
  {
    id: "DC_17_11",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_17_11-rgb.jpg",
    height: "/test-DC_17_11-height.jpg",
    depth: "/test-DC_17_11-depth.jpg",
    classes: "/test-DC_17_11-classes.jpg",
    thumb: "/test-DC_17_11-rgb.jpg",
    max: "22.1 m",
    buildingCoverage: 25.2,
    urban: true,
    split: "test",
  },
  {
    id: "DC_17_12",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_17_12-rgb.jpg",
    height: "/test-DC_17_12-height.jpg",
    depth: "/test-DC_17_12-depth.jpg",
    classes: "/test-DC_17_12-classes.jpg",
    thumb: "/test-DC_17_12-rgb.jpg",
    max: "20.4 m",
    buildingCoverage: 33.2,
    urban: true,
    split: "test",
  },
  {
    id: "DC_17_15",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_17_15-rgb.jpg",
    height: "/test-DC_17_15-height.jpg",
    depth: "/test-DC_17_15-depth.jpg",
    classes: "/test-DC_17_15-classes.jpg",
    thumb: "/test-DC_17_15-rgb.jpg",
    max: "24.6 m",
    buildingCoverage: 30.7,
    urban: true,
    split: "test",
  },
  {
    id: "DC_17_19",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_17_19-rgb.jpg",
    height: "/test-DC_17_19-height.jpg",
    depth: "/test-DC_17_19-depth.jpg",
    classes: "/test-DC_17_19-classes.jpg",
    thumb: "/test-DC_17_19-rgb.jpg",
    max: "40.4 m",
    buildingCoverage: 3.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_17_25",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_17_25-rgb.jpg",
    height: "/test-DC_17_25-height.jpg",
    depth: "/test-DC_17_25-depth.jpg",
    classes: "/test-DC_17_25-classes.jpg",
    thumb: "/test-DC_17_25-rgb.jpg",
    max: "41.7 m",
    buildingCoverage: 0.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_18_09",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_18_09-rgb.jpg",
    height: "/test-DC_18_09-height.jpg",
    depth: "/test-DC_18_09-depth.jpg",
    classes: "/test-DC_18_09-classes.jpg",
    thumb: "/test-DC_18_09-rgb.jpg",
    max: "25.4 m",
    buildingCoverage: 24.6,
    urban: false,
    split: "test",
  },
  {
    id: "DC_18_20",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_18_20-rgb.jpg",
    height: "/test-DC_18_20-height.jpg",
    depth: "/test-DC_18_20-depth.jpg",
    classes: "/test-DC_18_20-classes.jpg",
    thumb: "/test-DC_18_20-rgb.jpg",
    max: "37.2 m",
    buildingCoverage: 11.8,
    urban: false,
    split: "test",
  },
  {
    id: "DC_18_23",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_18_23-rgb.jpg",
    height: "/test-DC_18_23-height.jpg",
    depth: "/test-DC_18_23-depth.jpg",
    classes: "/test-DC_18_23-classes.jpg",
    thumb: "/test-DC_18_23-rgb.jpg",
    max: "43.9 m",
    buildingCoverage: 0.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_18_29",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_18_29-rgb.jpg",
    height: "/test-DC_18_29-height.jpg",
    depth: "/test-DC_18_29-depth.jpg",
    classes: "/test-DC_18_29-classes.jpg",
    thumb: "/test-DC_18_29-rgb.jpg",
    max: "18.7 m",
    buildingCoverage: 30.0,
    urban: true,
    split: "test",
  },
  {
    id: "DC_18_36",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_18_36-rgb.jpg",
    height: "/test-DC_18_36-height.jpg",
    depth: "/test-DC_18_36-depth.jpg",
    classes: "/test-DC_18_36-classes.jpg",
    thumb: "/test-DC_18_36-rgb.jpg",
    max: "20.2 m",
    buildingCoverage: 26.5,
    urban: true,
    split: "test",
  },
  {
    id: "DC_19_17",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_19_17-rgb.jpg",
    height: "/test-DC_19_17-height.jpg",
    depth: "/test-DC_19_17-depth.jpg",
    classes: "/test-DC_19_17-classes.jpg",
    thumb: "/test-DC_19_17-rgb.jpg",
    max: "27.6 m",
    buildingCoverage: 25.5,
    urban: true,
    split: "test",
  },
  {
    id: "DC_19_24",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_19_24-rgb.jpg",
    height: "/test-DC_19_24-height.jpg",
    depth: "/test-DC_19_24-depth.jpg",
    classes: "/test-DC_19_24-classes.jpg",
    thumb: "/test-DC_19_24-rgb.jpg",
    max: "41.5 m",
    buildingCoverage: 0.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_19_31",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_19_31-rgb.jpg",
    height: "/test-DC_19_31-height.jpg",
    depth: "/test-DC_19_31-depth.jpg",
    classes: "/test-DC_19_31-classes.jpg",
    thumb: "/test-DC_19_31-rgb.jpg",
    max: "16.9 m",
    buildingCoverage: 34.5,
    urban: true,
    split: "test",
  },
  {
    id: "DC_19_36",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_19_36-rgb.jpg",
    height: "/test-DC_19_36-height.jpg",
    depth: "/test-DC_19_36-depth.jpg",
    classes: "/test-DC_19_36-classes.jpg",
    thumb: "/test-DC_19_36-rgb.jpg",
    max: "26.8 m",
    buildingCoverage: 15.7,
    urban: false,
    split: "test",
  },
  {
    id: "DC_19_37",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_19_37-rgb.jpg",
    height: "/test-DC_19_37-height.jpg",
    depth: "/test-DC_19_37-depth.jpg",
    classes: "/test-DC_19_37-classes.jpg",
    thumb: "/test-DC_19_37-rgb.jpg",
    max: "31.2 m",
    buildingCoverage: 0.0,
    urban: false,
    split: "test",
  },
  {
    id: "DC_19_41",
    label: "GAMUS landscape tile",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_19_41-rgb.jpg",
    height: "/test-DC_19_41-height.jpg",
    depth: "/test-DC_19_41-depth.jpg",
    classes: "/test-DC_19_41-classes.jpg",
    thumb: "/test-DC_19_41-rgb.jpg",
    max: "18.4 m",
    buildingCoverage: 23.4,
    urban: false,
    split: "test",
  },
  {
    id: "DC_20_08",
    label: "Mixed urban district",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_20_08-rgb.jpg",
    height: "/test-DC_20_08-height.jpg",
    depth: "/test-DC_20_08-depth.jpg",
    classes: "/test-DC_20_08-classes.jpg",
    thumb: "/test-DC_20_08-rgb.jpg",
    max: "29.2 m",
    buildingCoverage: 25.1,
    urban: true,
    split: "test",
  },
  {
    id: "DC_20_11",
    label: "Urban building fabric",
    coord: "DFC 2019 · test tile",
    rgb: "/test-DC_20_11-rgb.jpg",
    height: "/test-DC_20_11-height.jpg",
    depth: "/test-DC_20_11-depth.jpg",
    classes: "/test-DC_20_11-classes.jpg",
    thumb: "/test-DC_20_11-rgb.jpg",
    max: "20.4 m",
    buildingCoverage: 30.1,
    urban: true,
    split: "test",
  },
];
// 135 additional source tiles; all 150 GAMUS triplets are represented after merging curated scenes.
